<?php

/* Nothing here! This is the "empty map," which is just water, water everywhere. */

$map = array(
	1 => array(
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
		),
	2 => array(
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
		),
	3 => array(
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
		),
	4 => array(
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
		),
	5 => array(
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
		),
	6 => array(
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
		),
	7 => array(
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
		),
	8 => array(
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
		),
	9 => array(
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
		),
	10 => array(
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
			array('water', ''),
		),
	);

?>