<?php

$map = array(
	1 => array(
		  	array('water', ''), 
		  	array('sand', array( 'fish' => 9, 'coal' => 2, 'arable land' => 2 )),
		  	array('hills', array( 'coal' => 8, 'iron' => 5, 'fish' => 4, 'arable land' => 1 )),
		  	array('mountains', array( 'iron' => 6, 'coal' => 4, 'uranium' => 4, 'fish' => 3 )),
		  	array('hills', array( 'coal' => 5, 'iron' => 4, 'fish' => 4 )), 
		  	array('grass', array( 'fish' => 8, 'arable land' => 7, 'sheep' => 3 )), 
		  	array('water', ''),
		  	array('water', ''),
		  	array('water', ''),
		  	array('water', ''),
		),
	2 => array(
			array('water', ''),  
			array('water', ''),  
			array('sand', array( 'fish' => 3 )), 
			array('mountains', array( 'uranium' => 7, 'iron' => 5, 'stone' => 3 )), 
			array('mountains', array( 'iron' => 8, 'stone' => 6, 'coal' => 4, 'gold' => 2 )), 
			array('hills', array( 'coal' => 10, 'arable land' => 2, 'sheep' => 2 )), 
			array('grass', array( 'arable land' => 7, 'sheep' => 5, 'fish' => 4 )), 
			array('sand', array( 'oil' => 5, 'fish' => 5)), 
			array('water', ''),  
			array('water', ''), 
		),
	3 => array(
			array('sand', array( 'fish' => 6 )), 
			array('sand', array( 'oil' => 3, 'fish' => 3 )), 
			array('hills', array( 'coal' => 7, 'arable land' => 5 )), 
			array('mountains', array( 'iron' => 4, 'stone' => 3, 'gold' => 1 )), 
			array('hills', array( 'coal' => 5, 'arable land' => 3, 'lumber' => 1 )), 
			array('hills', array( 'coal' => 5, 'lumber' => 5, 'iron' => 2 )), 
			array('hills', array( 'coal' => 7, 'lumber' => 2, 'arable land' => 2 )), 
			array('grass', array( 'arable land' => 8, 'sheep' => 5, 'fish' => 5 )), 
			array('water', ''), 
			array('water', ''),
		),
	4  => array(
			array('grass', array( 'fish' => 10, 'arable land' => 6 )), 
			array('grass', array( 'arable land' => 6, 'lumber' => 3, 'fish' => 2 )), 
			array('mountains', array( 'iron' => 8, 'uranium' => 3 )), 
			array('hills', array( 'coal' => 7, 'iron' => 5 )), 
			array('hills', array( 'iron' => 3, 'lumber' => 2 )), 
			array('forest', array( 'lumber' => 9, 'arable land' => 2 )), 
			array('forest', array( 'lumber' => 8, 'arable land' => 6 )), 
			array('grass', array( 'arable land' => 10, 'sheep' => 8, 'fish' => 1 )), 
			array('grass', array( 'arable land' => 8, 'sheep' => 6, 'fish' => 4 )), 
			array('water', ''),
		),
	5  => array(
			array('water', ''), 
			array('water', ''), 
			array('water', ''), 
			array('sand', array( 'fish' => 8 )), 
			array('forest', array( 'lumber' => 8, 'sheep' => 2 )), 
			array('forest', array( 'lumber' => 10 )), 
			array('grass', array( 'sheep' => 8, 'arable land' => 5, 'lumber' => 1 )), 
			array('grass', array( 'arable land' => 7, 'sheep' => 3 )), 
			array('grass', array( 'arable land' => 5, 'sheep' => 3 )), 
			array('sand', array( 'fish' => 7, 'sheep' => 1 )),
		),
	6  => array(
			array('water', ''), 
			array('water', ''), 
			array('water', ''), 
			array('water', ''), 
			array('grass', array( 'arable land' => 5, 'lumber' => 4, 'sheep' => 4 )), 
			array('forest', array( 'lumber' => 9, 'sheep' => 2 )), 
			array('grass', array( 'lumber' => 4, 'arable land' => 4 )), 
			array('hills', array( 'coal' => 6, 'iron' => 5 )), 
			array('grass', array( )), 
			array('sand', array( )),
		),
	7  => array(
			array('water', ''), 
			array('water', ''),
			array('grass', array( 'fish' => 10, 'arable land' => 4 )), 
			array('sand', array( 'fish' => 3, 'oil' => 1 )), 
			array('grass', array( 'arable land' => 6, 'fish' => 2 )), 
			array('grass', array( 'arable land' => 8, 'sheep' => 3, 'lumber' => 2 )), 
			array('grass', array( 'arable land' => 7, 'sheep' => 5 )), 
			array('grass', array( 'arable land' => 6, 'coal' => 1, 'fish' => 1 )), 
			array('sand', array( 'fish' => 4 )), 
			array('grass', array( 'arable land' => 2, 'sheep' => 2, 'fish' => 2 )),
		),
	8  => array(
			array('grass', array( 'sheep' => 8, 'arable land' => 6, 'fish' => 6 )), 
			array('grass', array( 'fish' => 9, 'sheep' => 7, 'arable land' => 3 )), 
			array('water', ''), 
			array('grass', array( 'fish' => 4, 'lumber' => 4, 'arable land' => 3 )), 
			array('forest', array( 'lumber' => 9, 'sheep' => 2 )), 
			array('forest', array( 'lumber' => 7, 'arable land' => 5 )), 
			array('grass', array( 'sheep' => 7, 'arable land' => 5 )), 
			array('water', ''), 
			array('water', ''), 
			array('water', ''),
		),
	9  => array(
			array('sand', array( 'fish' => 6 )), 
			array('hills', array( 'iron' => 10 )), 
			array('water', ''), 
			array('water', ''), 
			array('grass', array( 'arable land' => 5, 'fish' => 3)), 
			array('grass', array( 'sheep' => 6, 'arable land' => 4 )), 
			array('sand', array( 'fish' => 2 )), 
			array('grass', array( 'arable land' => 6, 'fish' => 2 )), 
			array('water', ''), 
			array('water', ''),
		),
	10 => array(
			array('water', ''), 
			array('grass', array( 'fish' => 8, 'sheep' => 4 )), 
			array('sand', array( 'fish' => 6 )), 
			array('sand', array( 'fish' => 5 )), 
			array('sand', array( 'fish' => 1 )), 
			array('sand', array( 'fish' => 1 )), 
			array('sand', array( 'fish' => 2 )), 
			array('grass', array( 'arable land' => 5, 'fish' => 3 )), 
			array('grass', array( 'arable land' => 4, 'sheep' => 4, 'fish' => 3 )), 
			array('water', ''),
		),
);
$neighbors = array(
	'nw' => 0,
	'n'  => 0,
	'ne' => 0,
	'w'  => 0,
	'e'  => 'secondo-1',
	'sw' => 0,
	's'  => 0,
	'se' => 'secondo-3',
);

?>