<?php

$map = array(
	1 => array(
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('grass', array('uranium' => 6, 'arable land' => 5, 'fish' => 5, 'sheep' => 3 )), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		),
	2 => array(
			array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		),
	3 => array(
		  	array('grass', array( 'sheep' => 5, 'lumber' => 3 )), 
		  	array('sand', array( 'fish' => 4 )), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('mountains', array( 'uranium' => 8, 'iron' => 6, 'stone' => 6, 'fish' => 5 )), 
		  	array('hills', array( 'stone' => 7, 'coal' => 7, 'fish' => 5 )), 
		  	array('water', ''),
		  	array('water', ''),
		),
	4  => array(
		  	array('forest', array( 'lumber' => 7, 'fish' => 1 )), 
		  	array('grass', array( 'sheep' => 7, 'arable land' => 3 )), 
		  	array('forest', array( 'fish' => 5, 'lumber' => 4 )), 
		  	array('grass', array( 'arable land' => 7, 'coal' => 1 )), 
		  	array('grass', array( 'sheep' => 5, 'arable land' => 3, 'fish' => 3 )), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		),
	5  => array(
			array('forest', array( 'lumber' => 8 )), 
		  	array('forest', array( 'lumber' => 10, 'stone' => 2 )), 
		  	array('hills', array( 'coal' => 7, 'iron' => 5 )), 
		  	array('grass', array( 'arable land' => 5 )), 
		  	array('grass', array( 'arable land' => 5, 'fish' => 1 )), 
		  	array('sand', array( 'fish' => 3 )), 
		  	array('sand', array( 'fish' => 10 )), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		),
	6  => array(
		  	array('hills', array( 'stone' => 5, 'coal' => 3 )), 
		  	array('hills', array( 'coal' => 7, 'iron' => 4 )), 
		  	array('mountains', array( 'stone' => 8, 'iron' => 7 )), 
		  	array('forest', array( 'lumber' => 10, 'stone' => 4 )), 
		  	array('sand', array( 'stone' => 3 )), 
		  	array('sand', array( 'fish' => 5 )), 
		  	array('water', ''), 
		  	array('water', ''), 
		    array('water', ''), 
		  	array('water', ''), 	
		),
	7  => array(
		  	array('water', ''), 
		  	array('hills', array( 'coal' => 6, 'uranium' => 2, 'fish' => 1 )), 
		  	array('mountains', array( 'coal' => 7, 'iron' => 7, 'gold' => 1 )), 
		  	array('hills', array( 'iron' => 7, 'stone' => 2 )), 
		  	array('sand', array( 'stone' => 1, 'fish' => 1 )), 
		  	array('sand', array( 'fish' => 6 )), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		),
	8  => array(
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('mountains', array( 'iron' => 8, 'stone' => 4 )), 
		  	array('mountains', array( 'stone' => 7, 'oil' => 3 )), 
		  	array('sand', array( 'fish' => 6 )), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		),
	9  => array(
			array('water', ''), 
		  	array('water', ''), 
		  	array('mountains', array( 'iron' => 5, 'coal' => 5, 'stone' => 5 )), 
		  	array('hills', array( 'coal' => 6, 'uranium' => 4, 'fish' => 4 )), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		),
	10 => array(
		  	array('water', ''), 
		  	array('hills', array( 'fish' => 5, 'iron' => 1 )), 
		  	array('mountains', array( 'iron' => 10, 'uranium' => 3 )), 
		  	array('hills', array( 'coal' => 4, 'lumber' => 2 )), 
		  	array('hills', array( 'coal' => 4, 'fish' => 3 )), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		  	array('water', ''), 
		),
);
$neighbors = array(
	'nw' => 0,
	'n'  => 0,
	'ne' => 0,
	'w'  => 'secondo-1',
	'e'  => 0,
	'sw' => 'secondo-3',
	's'  => 'secondo-4',
	'se' => 0,
);

?>